const selectors = {
    navTitle:'.nav__title',
    navItemFirst: '.nav__items_item-first',
    navItemSecond: '.nav__items_item-second',
    navItemThird: '.nav__items_item-third',
    navItemFour: '.nav__items_item-four',
    headerTitle: '.header__title',
    headerSubtitle: '.header__subtitle',
    headerText: '.header__text',
    headerButton: '.header__button-learn',
    projectsTitle: '.projects__title',
    footerTitle: '.footer__title',
    aboutTitle: '.about__title',
    aboutContentText: '.about__content_text',
    skillsTitle: '.skills__title',
    skillsItemTitle: '.skills__item_title',
    contactTitle: '.contacts__title',
    locationTitle: '.location',
    locationText: '.location-text',
    emailTitle: '.telegram',
    emailText: '.telegram-text',
    emailTitle: '.email',
    emailText: '.email-text',
}